name: Check

on:
    pull_request:
        branches: [ master, stable-* ]
    push:
        branches: [ master, stable-* ]

jobs:
    check:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                task: [ detekt, ktlintCheck, lint ]
        steps:
            -   uses: actions/checkout@v3
            -   name: Set up JDK 11
                uses: actions/setup-java@v3.5.1
                with:
                    distribution: "temurin"
                    java-version: 11
            -   name: Check ${{ matrix.task }}
                run: ./gradlew ${{ matrix.task }}
            - uses: actions/upload-artifact@v3
              if: ${{ always() }}
              with:
                  name: ${{ matrix.task }}-report
                  path: library/build/reports
